name: Update GitHub Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: nuelfell0ff
          options: theme=tokyo-night&hide_border=true&custom_title=Obaloluwa%20Emmanuel%20Ajayi's%20Contribution%20Graph
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish activity graph
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
